app:
  info: this is micro service of code（001）.
spring:
  rabbitmq:
    host: 10.211.55.6
    port: 5672
    username: admin
    password: aa121212
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.211.55.2:3306/admin?useSSL=false&characterEncoding=UTF8
    username: admin
    password: aa121212
